### PR TITLE
Improve default evaluation setting

### PR DESCRIPTION
**Pull request by arjenpdevries**
Address evaluation metrics to be reported on all topics (`-c` flag),
re: https://github.com/osirrc/jig/issues/105

And, report P@5 by default, just like the "official" evaluation at OSIRRC 2019.

### CODE REVIEW

**Comment by lintool** [comment]
@arjenpdevries I'll let @r-clancy look at this in case he's in the middle of something else.

**Comment by r-clancy** [comment]
I'll merge this, but for the rest of the official run through I'll keep P@30 in my local copy of jig so I can confirm P@30 numbers (which is what most people have in their README now).

**Comment by lintool** [comment]
@arjenpdevries would you be willing to change over to P@30 in OldDog to be consistent with others? The primary metrics we've decided on is NDCG@20, AP, and P@30, IIRC...

**Comment by arjenpdevries** [comment]
Definitely!
@Chriskamphuis can you update the table with the P@30 scores?

**Comment by Chriskamphuis** [comment]
After this merge we will find other values because of `-c` flag. I will update the values to those found when running with the `-c` flag.

**Comment by arjenpdevries** [comment]
Probably should only merge the - c modification then?
Shall I revert the P. 5 and reopen another pull request?

**Comment by r-clancy** [comment]
> Probably should only merge the - c modification then?
> Shall I revert the P. 5 and reopen another pull request?

Yeah, let's just do the `-c` change for now.

**Comment by arjenpdevries** [comment]
Ok 👌 later tonight

**Pull request closed without merging**
